# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

{
    'name': 'Aice Freezer Order Management',
    'version': '1.0.0',
    'category': 'Freezer Asset Management',
    'summary': '',
    'description': 'Modulo para administração de freezers da AICE',
    'live_test_url': '',
    'sequence': '1',
    'website': 'https://wwww.exemple.com',
    'author': 'João Victor',
    'maintainer': '',
    'license': 'LGPL-3',
    'support': '',
    'depends': ['mail','product', 'account', 'report_xlsx', 'web', 'sale', 'base', 'product', 'aice_br_custom_fields'],
    'demo': [],
    'data': [
        'security/ir.model.access.csv',
        'views/orders.xml',
        'views/products.xml',
        'views/resourceTypeView.xml',
        'views/resourceView.xml',
        'views/terminalMgmt.xml',
        'views/takebackReason.xml',
        'views/storeType.xml',
        'views/orderType.xml',
        'views/marketType.xml',
        'data/data.xml',
        'data/fom.ordertype.csv',
        'report/report.xml',
        'report/fom_report_template.xml'],
    'qweb': [],
    'js': [],
    'installable': True,
    'auto_install': False,
}
